service:
  name: sls-dd-missing-folder

provider:
  name: aws
  stage: dev
  runtime: python3.7
  region: us-west-2
  tracing:
    lambda: true
    apiGateway: true
  environment:
    ENV: ${self:provider.stage}

custom:
  pythonRequirements:
    slim: true
  datadog:
    logLevel: info
    flushMetricsToLogs: true

package:
  individually: true

plugins:
  - serverless-python-requirements
  - serverless-plugin-datadog

functions:
  f1:
    module: f1
    handler: handler.handler
  f2:
    module: f2
    handler: handler.handler
